---
# tasks file for ansible-api-github

## New block for CSV import option
- name: Mass Import Option
  block:
    - name: Read-in CSV
      community.general.read_csv:
        path: "{{ csv_location }}"
      register: csv_list
  when: csv_location is defined

- name: Evaluation Block
  block:
    - name: Query to see if the repo exists
      uri:
        url: "{{ github_apiUrl }}/user/repos?affiliation=owner"
        url_username: "{{ github_userAccount }}"
        url_password: "{{ github_userToken }}"
        force_basic_auth: yes
        method: GET
        status_code: 200
        body_format: json
      register: github_query

    - name: Convert to List
      set_fact:
        github_repos: "{{ github_repos|default([]) + [item.name] }}"
      with_items: "{{ github_query.json }}"

    - name: Current project in this API account
      debug:
        msg: "{{ github_repos}}"

- name: Create Repository - CSV
  include_tasks: git_create.yml
  when: csv_list.list is defined
  with_items: "{{ csv_list.list }}"

- name: Create Repository
  include_tasks: git_create.yml
